### ISSUE TITLE
Issues with running the code with oedometer data that does not have a reloading stage

### ISSUE THREAD

**Issue by KCaucisGM** [eamontoyaa/pySigmaP#1]
* pySigmaP version: 0.1.9
* Python version: 3.10.10
* Operating System: Windows 10 Pro

### Description

Tried to determine the preconsolidation pressure from oedometer test data. However the test data only had one loading and an unloading stage. The program does not seem to be able to run with such data throwing up and index error (below). It is reasonably frequent that reloading is not specified in the industry, therefore having a function to run without reloading curve would be useful.

FYI - I tested the code with the testData.csv provided and removing the reloading stage from that data resulted in the same error message.

   brkIdx1 = idx_unloading_init[self.use_this_UR_stage]
IndexError: list index out of range

Dataframe:
            Effective_Vertical_Stress  Axial_Strain  Void_Ratio
0                       123.0           0.0       0.791
1                       251.0           0.0       0.749
2                       498.0           0.0       0.723
3                      1001.0           0.0       0.674
4                      2002.0           0.0       0.612
5                      3999.0           0.0       0.548
6                      8002.0           0.0       0.464
7                     15999.0           0.0       0.357
8                     29001.0           0.0       0.246
9                      7248.0           0.0       0.141
10                     1814.0           0.0       0.222

### What I Did

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pysigmap.data import Data
from pysigmap.boone import Boone


input_data = r'XXXXXXXXXXXXXXX'
data_frame = pd.read_csv(input_data)
print(data_frame)

data = Data(data_frame, sigmaV=75)

method = Boone(data)
fig = method.getSigmaP()

**Comment by eamontoyaa** [comment]
Hi @KCaucisGM,

Thank you for testing pySigmaP.

I tested the code with the testData.csv as you did, by removing the unnecessary data such that it approaches to what you need.
The program worked normally by using the following code:

```
import pandas as pd
from pysigmap.data import Data
url = "".join(
    [
        "https://raw.githubusercontent.com/",
        "eamontoyaa/data4testing/",
        "main/pysigmap/testData.csv",
    ]
)
raw_data = pd.read_csv(url)
raw_data = raw_data.iloc[0: 15].copy()  # Here, I removed reloading data
data = Data(raw_data, sigmaV=75, reloading=False, secondUnloading=False)
fig = data.plot() 
```

I believe that the trick is not forgetting to include `reloading=False, secondUnloading=False` in the inputs of the Data class.

The same can be done using your data. However, it must also be checked since there is an unexpected behavior in your unloading stage. Usually, the more you unload the oedometer, the more increases the void ratio. The input data must include a first row with sigma_v=0 and the initial void ratio in the third column.
Please, see the modified version of the input data I prepared to demonstrate that pySigmaP should work.

```
Effective_Vertical_Stress, Axial_Strain, Void_Ratio
0, 0, 0, 0.795
1, 123.0, 0.0, 0.791
2, 251.0, 0.0, 0.749
3, 498.0, 0.0, 0.723
4, 1001.0, 0.0, 0.674
5, 2002.0, 0.0, 0.612
6, 3999.0, 0.0, 0.548
7, 8002.0, 0.0, 0.464
8, 15999.0, 0.0, 0.357
9, 29001.0, 0.0, 0.246
10, 7248.0, 0.0, 0.3
11, 1814.0, 0.0, 0.35
```

And, by running the following code, you should not receive any error:

```
import pandas as pd
import numpy as np
from pysigmap.data import Data
from pysigmap.boone import Boone

# This allows previsualizing the input data
data = Data(
    pd.read_csv("data.csv"),
    sigmaV=150,
    reloading=False,
    secondUnloading=False
)
fig = data.plot()

# This modifies some parameters for a "better" calculation of Cc and Cr
data.compressionIdx(range2fitCc=(8000, np.inf))
data.recompressionIdx(opt=2)
fig = data.plot()

# This runs the Boone method
boone_method = Boone(data)
fig7 = boone_method.getSigmaP()
```

Please, let me know if it runs as expected or if any problem persists.

Regards, Exneyder.

**Comment by KCaucisGM** [comment]
Hi Exneyder,

Thank you very much for the prompt reply. This has solved the issue, I had not noticed the roalding/secondUnloading options. I managed to get it to work for my data. Thank you for solving it and also for sharing your code. It is a really useful tool!
Is there a way to record the the pre-consolidation pressure and other parameters (Cc, Cr) other than on the figure, i.e. is there a function that returns those as variables? 

Thanks again,
Regards,
Karlis

**Comment by eamontoyaa** [comment]
@KCaucisGM 
Hi Karlis,

You can get the values of Cc, Cr, and even σ_p by exploring the attributes of their respective object.
For instance, Cc and Cr are calculated within the class Data, so the object you create from that class will contain them. The values are returned if you run `data.idxCc` and `data.idxCr`, respectively.

On the other hand, σ_p is calculated within the class related to the method. Again, in the above example, if you run `boone_method.sigmaP`, you will obtain the value calculated through the Boone method.

All the attributes of any object created using pySigmaP can be explored by running `object_created.__dict__`.

Do not hesitate if you have any additional question.

Regards,
Exneyder M.
